"""Add new field to User model

Revision ID: 486677e20d56
Revises: 
Create Date: 2025-07-03 19:59:11.704086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '486677e20d56'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('winner_result', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('winner_result')

    # ### end Alembic commands ###
